services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokenizer_hardhat
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # Keep the container running in the background
    tty: true
